version: "3"
services:
  database:
    container_name: "database"
    image: mysql/mysql-server:5.7

    volumes:
      - ./mysql/mysqlconf:/etc/mysql/conf.d
      - ./mysql/init-data/aaschema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/init-data/data.sql:/docker-entrypoint-initdb.d/2.sql
      - ./mysql/database:/var/lib/mysql
    #  ports:
    #    - "3306:3306"
    restart: always

  app:
  # tu trzeba zmienic na gornikprzemyslaw/app jak PrzemeG wywali https w obrazie
    image: app
    depends_on:
      - database
  #  ports:
  #    - "8080:8080"
  #    - "9990:9990"
  #    - "8443:8443"

  reverse-proxy:
    image: nginx:1.17.10
    container_name: "nginx_reverse_proxy"
    depends_on:
      - app
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/server.crt:/etc/nginx/certs/server.crt
      - ./certs/server.key-bezhasla:/etc/nginx/certs/server.key
    ports:
      #   - "80:80"
      - "443:443"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 5431:8080/tcp
    container_name: adminer