version: "3"
services:
  database:
    image: mysql/mysql-server:5.7
    volumes:
      - ./mysql/mysqlconf:/etc/mysql/conf.d
      - ./mysql/init-data:/docker-entrypoint-initdb.d
      - ./mysql/mysql-data:/var/lib/mysql
    restart: always

  app:
    image: app
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8443:8443"
