version: "3"
services:
  database:
    image: mysql/mysql-server:5.7
    volumes:
      - "/Users/pawelbialek/tua:/var/lib/mysql"
    ports:
      - "3306:3306"
  app:
    image: app
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8443:8443"
