version: "3"
services:
  database:
    image: mysql/mysql-server:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init-data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    image: app
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8443:8443"
